### ISSUE TITLE
struct: constraints and types

### ISSUE THREAD

**Issue by Deleetdk** [stefano-meschiari/dict#3]
One can cause havoc by having a struct that has constraints and giving them arguments that have a wrong type. For instance:

```
> PositiveVector <- struct('PositiveVector',
+                          x = 1 ~ { x > 0 },
+                          y = 1 ~ { y > 0 },
+                          z = 1 ~ { z > 0 })
> PositiveVector(x = "sd")
Struct of class  PositiveVector 
$ x : [1] "sd"
$ y : [1] 1
$ z : [1] 1
```

Here we supposedly have a vector of positive values, except that one of the values is a `chr`. It's because `chr` apparently always satisfies `> 0`:

```
> "a" > 0
[1] TRUE
> "a" < 0
[1] FALSE
> "a" == 0
[1] FALSE
> "test" > 0
[1] TRUE
```

Not sure what the semantics for comparing `chr` to `num` is in R. You probably want to force a type check for these too.

**Comment by stefano-meschiari** [comment]
Moving this to a separate `struct` package.
